"""create dwell_time migrations

Revision ID: e41662395f22
Revises: 
Create Date: 2023-06-20 01:25:12.270563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41662395f22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=120), nullable=False),
    sa.Column('login_url', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dwell_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_dwell_times', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['web_id'], ['web_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('web_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['web_id'], ['web_client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model')
    op.drop_table('dwell_time')
    op.drop_table('web_client')
    # ### end Alembic commands ###
